id = 5
title = "Cyber Academy: File Forensics"
short = "File Forensics" 
date = "Wednesday 11/2 8:00PM-10:00PM PT"
description = """Ever wondered what *really* goes on inside files?? ğŸ¤”ğŸ§ We might know theyâ€™re all full of 01001100â€™s or whatever, but those have to mean something! Come join Cyber as we first take a look at what a file really is (â‰ï¸) and then jump into disassembling files and learning how to be a ğŸ•µï¸ file detective. See the traces left behind in your â€œdigital footprintâ€ and how data can be hidden in seemingly plain sight! Pull up to the File Forensics workshop for all this fun *and* to see our handsome faces ğŸ˜‰ (2 in 1!!)
"""
link = "https://fb.me/e/1Vr7V2eJg"
slides = ""
