slug = "steg-feedback"
title = "Feedback Form"
author = "loltyler1dotcom-discount-code-alpha"
value = 10
description = """Fill out the feedback form [here](https://forms.gle/5MUa1AyPBeRRJWCv5) is a picture."""
tags = [ "feedback" ]
files = []
flag = "flag{f33db@cck}"
enabled = true
