
slug = "file-demo-1"
title = "File Demo 1"
author = "Luke"
value = 5
description = """The first demo of the file forensics workshop. Demo file [here](file_demo). Submission flag is all individual flags underscore separated: flag{flag1_flag2_flag3_flag4}."""
tags = [ "file analysis" ]
files = [ "file_demo" ]
flag = "flag{i_think_you_have_to_leave_a_space}"
enabled = true
