slug = "linux-feedback"
title = "Linux & Scripting Feedback"
author = "Salma"
value = 10
description = """Please fill out this feedback [form](https://forms.gle/86LRFgAE9EEabSY37) to let us know your thoughts about the workshop! You will receive the flag at the end!"""
tags = [ "scripting" ]
files = []
flag = "flag{command_line_genius}"
enabled = true