id = 8
title = "CTF After Dark"
short = "CTF After Dark" 
date = "Wednesday 11/16 8:00PM-10:00PM PT"
description = """*Insert ğŸ”¥hype ğŸ”¥main character music hereâ€¼ï¸* Imagineâ€¦ ğŸ’­Youâ€™ve been trainingğŸ‹ï¸all quarter (Â¼) long for this. Youâ€™ve been walking up those 9ï¸âƒ£ flights of stairs for this ğŸ¦µğŸ¥µ. Youâ€™re tired ğŸ˜£. Momâ€™s spaghetti ğŸ. But you donâ€™t care ğŸ™…ğŸ™…â€â™€ï¸ğŸ™…â€â™‚ï¸. Your megamind brain ğŸ§  is ready for anything that comes your way. You are a Cookie ğŸª Monster ğŸ”µğŸ‘„ğŸ”µ. You, my dear friend ğŸ¦Œ, are an absolute unit.
But anywho, come play our ğŸš© Capture the Flag (CTF)  ğŸš©competition ğŸ•¸ğŸ‘¨â€ğŸ’» and FLEX ğŸ’ª off all that youâ€™ve learned from our workshops this Fall ğŸ. Winners ğŸ…will be rewarded ğŸ‘€. Be there or be square ğŸŸ¨. CTF Time Event: https://ctftime.org/event/1780
"""
link = ""
slides = ""
