id = 1
title = "ACM Cyber Fall GM"
short = "Fall GM"
date = "Friday 9/30 6:00PM-8:00PM PT"
description = """ğŸ§© Like solving technical puzzles? ğŸ–¥ Want to learn all the extra, juicy details of computers? ğŸ¯ Curious how organizations are attacked, both digitally and socially? If you said "yes" to any of these, ACM Cyber is the club for you! ğŸ”
Come on over to Cyber's Fall General Meeting on Friday, September 30th from 6 to 8 pm at Kerckhoff Hall 133 + 135 to learn more about what we do, meet the officers, befriend some like-minded individuals, and try solving some challenges! Bring your lassos (actually please don't), it's ğŸ‘¢cowgirl/boy/person themedğŸ´! No experience necessary :)
(note: bring a laptop to delve into the cool challenges! or share one with someone you meet!)
"""
link = "https://fb.me/e/1RydScfhF"
slides = ""
