slug = "endless-pdf"
title = "Endless PDF"
author = "James"
value = 10
description = """wow look at this endless [pdf](endless.pdf)! okay its not really endless but its pretty long and full of random characters, can you help me see if the flag is anywhere?"""
tags = [ "file analysis" ]
files = ["endless.pdf"]
flag = "flag{end_0f_fi1e}"
enabled = true