slug = "cbum-natty"
title = "Is @cbum (3x Mr. Olympia/Handsome Gigachad Alphamale) Natty???"
author = "loltyler1dotcom-discount-code-alpha"
value = 10
description = "@cbum (follow on IG rn) has a secret. Being the bigbrained alphamale gigachad he is, he wrote a [script](encode.py) to hide his secret in this (picture)[3-cbum.jpeg]."
tags =[ "steg" ]
files = [ "encode.py", "3-cbum.jpeg" ]
flag = "flag{@cbum_1$_N@TTY}"
enabled = true
