slug = "heisenbones"
title = "Heisenbones"
author = "Rory"
value = 50
description = """I'm rewatching breaking bad and apparently there's [this](heisenbones.png) ridiculous skeleton character named heisenbones??? I don't remember this at all"""
tags = [ "scripting", "stego" ]
files = [ "heisenbones.png" ]
flag = "flag{new_mandela_effect_just_dropped}"
enabled = true
