
slug = "file-demo-2"
title = "File Demo 2"
author = "Luke"
value = 5
description = """The second demo of the file forensics workshop. Demo file [here](demo2.zip). Submission flag is all individual flags underscore separated: flag{flag1_flag2}."""
tags = [ "file analysis" ]
files = [ "demo2.zip" ]
flag = "flag{walk_that_bin}"
enabled = true
