slug = "birds"
title = "Birds"
author = "Stephen"
value = 20
description = """I like listening to bird sounds, but it's really annoying when I only hear it in one ear at a time. Can you help me fix [this audio](birds.wav)?"""
tags = [ "steganography" ]
files = [ "birds.wav" ]
flag = "flag{mono_audio_remaster}"
enabled = true
